export {
  getInvitation,
  acceptInvitation,
  getRequestAccessInfo,
  approveRequestAccess,
  sendRequestAccess,
  getShareDetail,
  sharePageTo,
  revokeAccess,
  turnIntoMember,
  getShareWithMe,
  grantObjectAccess,
  getObjectGrants,
  revokeObjectGrant,
} from '../js-services/http/access-api';
